# Site settings
title: Lead and Galvanized Pipe Inspection
description: "Schedule an inspection of your home's pipes, to keep your family safe from lead contamination and in line with new, better water standards."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png

# Hero
hero: 
    hero_img: water-kitchen-black-design.jpg
    hero_title: Lead & Galvanized Pipe Inspection
    hero_description: Schedule an inspection of your home's pipes, to keep your family safe from lead contamination and in line with new, better water standards.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: contact@yoursite.com
    address: 33 Highland Avenue, <br> Rowayton CT 06853

# Opening hours
monday_friday: 9:00 – 6:00
saturday: 10:00 – 5:00
sunday: 10:00 – 5:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 33 Highland Avenue, Rowayton CT 06853, USA
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2016 United Lead and Galvanized Pipe Inspection - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
